services:
  app-dev:
    user: node
    container_name: notes_api_dev
    build:
      context: .
      target: development
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./coverage:/app/coverage
      - .:/app
      - /app/node_modules
  mongo:
    container_name: notes_api_mongodb_dev
    image: mongo
    ports:
      - 27019:27017
    expose:
      - 27017
    volumes:
      - ./data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 3
volumes:
  data:
  coverage:
