# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: tests
    env:
      DB_URI: ${{ secrets.DB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CONNECTION_POOL_SIZE: ${{ vars.CONNECTION_POOL_SIZE }}
      DB_NAME: ${{ vars.DB_NAME }}
      PORT: ${{ vars.PORT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Docker Compose and build
        run: docker-compose -f docker-compose.ci.yml up --force-recreate --build -d

      - name: Run Tests
        run: docker exec notes_api_ci npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.ci.yml down
